const ShopActionTypes = {
  FETCH_TEXTBOOKS_START: 'FETCH_TEXTBOOKS_START',
  FETCH_TEXTBOOKS_SUCCESS: 'FETCH_TEXTBOOKS_SUCCESS',
  FETCH_TEXTBOOKS_FAILURE: 'FETCH_TEXTBOOKS_FAILURE',
};

export default ShopActionTypes;
